apiVersion: v1
kind: Service
metadata:
  name: graval-external
  labels:
    {{- include "graval.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.graval.service.nodePort }}
      port: {{ .Values.graval.service.port }}
      targetPort: {{ .Values.graval.service.targetPort }}
      name: validator-graval
  selector:
    {{- include "graval.labels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: graval
  labels:
    {{- include "graval.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.graval.service.port }}
      targetPort: {{ .Values.graval.service.targetPort }}
      name: validator-graval
  selector:
    {{- include "graval.labels" . | nindent 4 }}
