apiVersion: apps/v1
kind: Deployment
metadata:
  name: graval
  labels:
    {{- include "graval.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.graval.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "graval.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graval.labels" . | nindent 8 }}
    spec:
      {{- with .Values.graval.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graval.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graval.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      runtimeClassName: nvidia-container-runtime
      containers:
        - name: graval
          image: "{{ .Values.graval.image }}"
          imagePullPolicy: {{ .Values.graval.imagePullPolicy }}
          command: ["python", "api.py", "--port", "{{ .Values.graval.service.targetPort }}", "--validator-whitelist", "{{ join "," .Values.graval.validatorWhitelist }}", "--block-external"]
          ports:
            - name: http
              containerPort: {{ .Values.graval.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.graval.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.graval.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.graval.livenessProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.graval.livenessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.graval.livenessProbe.failureThreshold | default 3 }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: {{ .Values.graval.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.graval.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.graval.readinessProbe.timeoutSeconds | default 5 }}
            successThreshold: {{ .Values.graval.readinessProbe.successThreshold | default 1 }}
            failureThreshold: {{ .Values.graval.readinessProbe.failureThreshold | default 3 }}
          resources:
            {{- toYaml .Values.graval.resources | nindent 12 }}
