apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gravaldb-network-policy
  labels:
    {{- include "gravaldb.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gravaldb.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: graval
      ports:
        - protocol: TCP
          port: 5432
    {{- if .Values.datadog_enabled }}
    - from:
        - podSelector:
            matchLabels:
              agent.datadoghq.com/component: "agent"
    {{- end }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
