graval:
  replicaCount: 8
  image: parachutes/graval:latest
  imagePullPolicy: Always
  validatorWhitelist:
    - 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
      nvidia.com/gpu: "1"
    limits:
      cpu: "1"
      memory: "4Gi"
      nvidia.com/gpu: "1"
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
    nodePort: 32002
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: In
            values: ["true"]
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - graval
          topologyKey: kubernetes.io/hostname
  tolerations: []

gravaldb:
  image: postgres:16
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  service:
    port: 5432
    targetPort: 5432
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: In
            values: ["true"]
  tolerations: []
