- name: Enable k8s extras
  hosts: all
  become: yes
  tasks:
    - name: Enable community plugins and third-party helm charts
      shell: |
        microk8s enable community || (sleep 10 && microk8s enable community) || true
        microk8s helm repo add nvidia https://helm.ngc.nvidia.com/nvidia || true
        microk8s helm repo update
      ignore_errors: yes

    - name: Install GPU Operator
      shell: |
        microk8s helm upgrade --install gpu-operator nvidia/gpu-operator \
          --namespace gpu-operator \
          --create-namespace \
          --set nodeSelector.kubernetes.io/gpu="true" \
          --set driver.enabled=true \
          --set toolkit.enabled=true \
          --set devicePlugin.enabled=true \
          --set operator.runtimeClass="nvidia-container-runtime" \
          --set operator.defaultRuntime=containerd \
          --set containerRuntime.socketPath=/var/snap/microk8s/common/run/containerd.sock
