all:
  vars:
    ssh_keys:
      - "ssh-rsa AAAAB3Nz..."
    user: jdurbin
    ansible_user: ubuntu
    is_primary: false
    ansible_ssh_common_args: '-o ControlPath=none'
    ansible_ssh_retries: 3
    cuda_version: "12.8"
    nvidia_version: "570"
    skip_cuda: false
    ubuntu_major: "24"
    ubuntu_minor: "04"
    ipv6_enabled: false

  hosts:
    graval-0:
      ansible_host: 1.2.3.4
